apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: tc-topic
  namespace: cloudflow
  labels:
    strimzi.io/cluster: cloudflow-strimzi
spec:
  partitions: 10
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: bundle-topic
  namespace: cloudflow
  labels:
    strimzi.io/cluster: cloudflow-strimzi
spec:
  partitions: 10
  replicas: 2